#!/usr/bin/env node

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import zlib from "node:zlib";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const MARKER = "<!-- mehen-metrics -->";
const DEFAULT_TITLE = "## 📊 Source Code Metrics";
const FOOTER_PREFIX =
  "> Generated by [mehen](https://github.com/ophi-dev/mehen)";
const FOOTER_SUFFIX = "— the code quality watcher.";
const LOWER_IS_BETTER = "lower-is-better";
const HIGHER_IS_BETTER = "higher-is-better";

const DEFAULT_TEST_EXCLUDES = [
  // Go
  "**/*_test.go",
  // Python
  "**/test_*.py",
  "**/*_test.py",
  "**/tests/**",
  "**/test/**",
  // JavaScript / TypeScript
  "**/__tests__/**",
  "**/*.test.js",
  "**/*.test.jsx",
  "**/*.test.ts",
  "**/*.test.tsx",
  "**/*.test.mjs",
  "**/*.test.cjs",
  "**/*.spec.js",
  "**/*.spec.jsx",
  "**/*.spec.ts",
  "**/*.spec.tsx",
  "**/*.spec.mjs",
  "**/*.spec.cjs",
  // Ruby
  "**/*_test.rb",
  "**/*_spec.rb",
  "**/spec/**",
];

const METRIC_ALIASES = new Map([
  ["functions", "nom.functions"],
  ["nom", "nom.functions"],
  ["lloc", "loc.lloc"],
  ["loc", "loc.lloc"],
  ["halsteadvol", "halstead.volume"],
  ["halsteadvolume", "halstead.volume"],
]);

// Declared above the entrypoint block below: `main()` starts running
// during module evaluation, so any `const` it reaches synchronously
// must already be initialized (a later declaration would be a
// temporal-dead-zone crash — seen live as "Cannot access
// 'CODECOV_PENDING_RETRIES' before initialization").
const CODECOV_PENDING_RETRIES = 3;
const CODECOV_RETRY_DELAY_MS = 5000;
// Mirrors mehen's own per-report ingestion cap (256 MiB): a base
// artifact bigger than that could never be fed to the CLI anyway.
// Enforced in three layers — artifact metadata, downloaded bytes, and
// declared/actual decompressed size — so a hostile or corrupt archive
// degrades instead of exhausting the runner.
const ARTIFACT_MAX_BYTES = 256 * 1024 * 1024;
// Artifact listings are newest-first; a base SHA older than ~1000
// same-named uploads is better served by the lower rungs than by an
// unbounded listing walk.
const ARTIFACT_MAX_PAGES = 10;
const ARTIFACT_DOWNLOAD_TIMEOUT_MS = 60_000;

if (isEntrypoint()) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}

function isEntrypoint() {
  return (
    process.argv[1] &&
    path.resolve(process.argv[1]) ===
      path.resolve(fileURLToPath(import.meta.url))
  );
}

async function main() {
  const thresholds = parseThresholds(input("THRESHOLDS"));
  const context = readGithubContext();
  let baseCoverage = await resolveBaseCoverage(context);
  const cli = prepareMehen();
  const version = detectMehenVersion(cli);
  let diffArgs = buildDiffArgs(baseCoverage.args);
  let diff;
  try {
    diff = runMehen(cli, diffArgs, { acceptGateOutput: isGateFailureReport });
  } catch (error) {
    // mehen hard-errors on an explicit report it cannot read or parse
    // — correct for a CLI gate input, but the retrieved base reports
    // are not fully controlled (a prefix cache key can restore another
    // configuration's files; an interrupted run can cache a truncated
    // report). The ladder's contract is disclosure and degradation,
    // never a failed action with no comment: retry once without the
    // base side and disclose the downgrade.
    if (!isBaseCoverageFailure(error, baseCoverage.args)) {
      throw error;
    }
    console.warn(
      "mehen rejected the retrieved base coverage report(s); continuing without base coverage.",
    );
    baseCoverage = {
      args: [],
      disclosure: `Base coverage: a retrieved report for \`${context.baseSha.slice(0, 7)}\` was unusable — coverage values are shown without a base to compare against, not as trends.`,
    };
    // Rebuild — not just rerun — so every later consumer of the
    // argument list (the Markdown docs rerun) also sees the degraded
    // arguments instead of re-tripping over the rejected report.
    diffArgs = buildDiffArgs();
    diff = runMehen(cli, diffArgs, {
      acceptGateOutput: isGateFailureReport,
    });
  }
  const reportsDir = process.env.RUNNER_TEMP || os.tmpdir();
  const reportJson = path.join(reportsDir, `mehen-diff-${Date.now()}.json`);
  fs.writeFileSync(reportJson, `${diff.stdout.trim()}\n`, "utf8");

  const diffs = parseDiffJson(diff.stdout);
  const gateViolations = parseGateViolations(diff.stdout);
  const violations = collectThresholdViolations(diffs, thresholds);
  let markdown = renderMarkdown(
    diffs,
    context,
    thresholds,
    violations,
    version,
    gateViolations,
    baseCoverage.disclosure,
  );

  // Phase F (§39): `mehen diff --output-format markdown` emits a
  // `<!-- mehen-docs -->` block whenever a changed Markdown file is in
  // scope. The JSON payload already says whether that is the case
  // (its `markdown` array), so the second invocation — needed only
  // for the *rendered* section — is skipped entirely when no Markdown
  // file changed, and runs history-free when it is needed.
  const docsSection = diffJsonHasDocs(diff.stdout)
    ? fetchMarkdownDocsSection(cli, diffArgs)
    : null;
  if (docsSection) {
    markdown = `${markdown.trimEnd()}\n\n${docsSection}\n`;
  }

  const reportMarkdown = path.join(reportsDir, `mehen-report-${Date.now()}.md`);
  fs.writeFileSync(reportMarkdown, markdown, "utf8");

  writeStepSummary(markdown);
  try {
    await maybeComment(markdown, context);
  } catch (error) {
    console.warn(`Unable to publish mehen PR comment: ${error.message}`);
  }

  // The advertised violation count covers both gates: Action-input
  // delta thresholds and repository `mehen.toml` breaches parsed from
  // the diff report.
  setOutput("violations", String(violations.length + gateViolations.length));
  setOutput("report_json", reportJson);
  setOutput("report_markdown", reportMarkdown);

  if (violations.length > 0 && boolInput("FAIL_ON_THRESHOLD", true)) {
    console.error(
      `Mehen threshold check failed with ${violations.length} violation(s).`,
    );
    process.exit(1);
  }

  // A deferred quality-gate failure from the diff itself (configured
  // `mehen.toml` thresholds): the comment and report outputs above
  // landed with the complete report; now the workflow step fails.
  if (diff.gateStatus) {
    console.error(
      `mehen diff exited with status ${diff.gateStatus}: a configured quality gate failed (see the report above).`,
    );
    process.exit(1);
  }
}

function input(name, fallback = "") {
  return process.env[`GHA_MEHEN_${name}`] ?? fallback;
}

function boolInput(name, fallback) {
  const value = input(name).trim().toLowerCase();
  if (!value) {
    return fallback;
  }
  return ["1", "true", "yes", "on"].includes(value);
}

function parseList(value) {
  const trimmed = String(value ?? "").trim();
  if (!trimmed) {
    return [];
  }
  const parts = trimmed.split(/\r?\n|[;,]/);
  return parts.map((part) => part.trim()).filter(Boolean);
}

function buildDiffArgs(extraArgs = []) {
  const args = ["diff", "--output-format", "json"];
  const from = input("FROM").trim();
  const to = input("TO").trim();
  const metrics = input("METRICS").trim();
  const paths = parseList(input("PATHS"));
  const include = parseList(input("INCLUDE"));
  const exclude = parseList(input("EXCLUDE"));
  const coverageFiles = parseList(input("COVERAGE_FILES"));
  if (boolInput("EXCLUDE_TESTS", true)) {
    for (const pattern of DEFAULT_TEST_EXCLUDES) {
      if (!exclude.includes(pattern)) {
        exclude.push(pattern);
      }
    }
  }

  if (from) {
    args.push("--from", from);
  }
  if (to) {
    args.push("--to", to);
  }
  if (metrics) {
    args.push("--metrics", metrics);
  }
  if (paths.length > 0 && !(paths.length === 1 && paths[0] === ".")) {
    args.push("--paths", ...paths);
  }
  if (include.length > 0) {
    args.push("--include", ...include);
  }
  if (exclude.length > 0) {
    args.push("--exclude", ...exclude);
  }
  if (boolInput("SHOW_UNCHANGED", false)) {
    args.push("--show-unchanged");
  }
  // Head-side coverage: the reports the caller's test step just wrote.
  // A configured-but-missing file is warned about and skipped rather
  // than passed through — mehen hard-errors on missing explicit
  // reports (an explicit gate input that silently disappears is a
  // broken gate), but the action is a reporter: the caller's test
  // step owns failing the build when coverage generation breaks.
  const presentCoverageFiles = coverageFiles.filter((file) => {
    if (fs.existsSync(file)) {
      return true;
    }
    console.warn(
      `mehen: coverage file '${file}' not found; head-side coverage will be missing for it`,
    );
    return false;
  });
  for (const file of presentCoverageFiles) {
    args.push(`--coverage=${file}`);
  }
  // Every configured report is missing: pin coverage off. Without the
  // pin, a `--base-coverage` argument would flip mehen's lazy trigger
  // into head-side auto-discovery, silently substituting whatever
  // stale artifact the working tree happens to hold for the reports
  // the caller explicitly configured.
  if (coverageFiles.length > 0 && presentCoverageFiles.length === 0) {
    args.push("--coverage=off");
  }
  args.push(...extraArgs);

  return args;
}

// ── Base coverage retrieval (issue #248, artifact rung: #254) ────────
//
// The action, not the mehen binary, owns base-revision coverage: mehen
// stays network-free and receives plain report paths. Degradation
// ladder: exact cache hit → workflow artifact by base SHA → codecov by
// SHA → nearest default-branch cache (recency-based, so explicitly
// disclosed) → absent (columns render as new measurements). Every
// level is stated in the sticky PR comment — never silently.

/**
 * Resolve base-revision coverage into `--base-coverage=` CLI arguments
 * plus a human-readable disclosure line for the PR comment. Returns
 * `{ args: [], disclosure: null }` when base coverage does not apply
 * (no coverage-files configured, source off, or not a pull request).
 */
async function resolveBaseCoverage(context) {
  const none = { args: [], disclosure: null };
  const files = parseList(input("COVERAGE_FILES"));
  const source =
    input("COVERAGE_BASE_SOURCE", "auto").trim().toLowerCase() || "auto";
  if (files.length === 0 || source === "off") {
    return none;
  }
  if (!["auto", "cache", "artifact", "codecov"].includes(source)) {
    throw new Error(
      `Unsupported coverage-base-source '${source}'. Use auto, cache, artifact, codecov, or off.`,
    );
  }
  const artifactName = input("COVERAGE_ARTIFACT_NAME").trim();
  if (source === "artifact" && !artifactName) {
    throw new Error(
      "coverage-base-source: artifact requires the coverage-artifact-name input.",
    );
  }
  // Base trends are a pull-request concept: pushes and manual runs
  // compare event-defined ranges whose base has no retrievable report.
  if (context.eventName !== "pull_request" || !context.baseSha) {
    return none;
  }
  const shortBase = context.baseSha.slice(0, 7);

  const cacheDir = input("COVERAGE_BASE_DIR").trim();
  const exactHit = input("COVERAGE_CACHE_HIT").trim().toLowerCase() === "true";
  const matchedKey = input("COVERAGE_CACHE_KEY").trim();
  const cachedReports = listFilesRecursively(cacheDir);

  // Rung 1 — exact cache hit: the base SHA's own reports.
  if (source !== "codecov" && source !== "artifact") {
    if (exactHit && cachedReports.length > 0) {
      return {
        args: cachedReports.map((file) => `--base-coverage=${file}`),
        disclosure: `Base coverage: restored from the Actions cache for \`${shortBase}\`.`,
      };
    }
  }

  // Rung 2 — workflow artifact by exact base SHA. Artifacts persist
  // ~90 days (the Actions cache evicts after 7 unused days or under
  // repository size pressure), and many repositories already upload
  // their coverage reports as artifacts — including for GitHub Code
  // Quality's own upload job. Requires `actions: read` on the job's
  // token; opt-in via the coverage-artifact-name input.
  if ((source === "auto" || source === "artifact") && artifactName) {
    const artifactFiles = await fetchArtifactBaseReports(
      context,
      artifactName,
    );
    if (artifactFiles) {
      return {
        args: artifactFiles.map((file) => `--base-coverage=${file}`),
        disclosure: `Base coverage: restored from the \`${artifactName}\` workflow artifact for \`${shortBase}\`.`,
      };
    }
  }

  // Rung 3 — codecov by exact SHA. Line dimension only: codecov's
  // merged view has no original branch arms, and fabricating BRDA
  // records would poison branch-coverage gates.
  if (source === "auto" || source === "codecov") {
    const lcov = await fetchCodecovBaseReport(context);
    if (lcov) {
      const dir = path.join(
        process.env.RUNNER_TEMP || os.tmpdir(),
        "mehen-codecov-base",
      );
      fs.mkdirSync(dir, { recursive: true });
      const reportPath = path.join(dir, "codecov-base.lcov");
      fs.writeFileSync(reportPath, lcov, "utf8");
      return {
        args: [`--base-coverage=${reportPath}`],
        disclosure: `Base coverage: fetched from codecov.io for \`${shortBase}\` (line dimension only).`,
      };
    }
  }

  // Rung 4 — nearest default-branch cache via the prefix restore-key:
  // recency-based, not ancestor-aware, so the staleness is disclosed
  // (mehen itself also warns when the report predates the base
  // commit).
  if (source !== "codecov" && source !== "artifact") {
    if (cachedReports.length > 0) {
      const label = matchedKey ? ` (\`${matchedKey}\`)` : "";
      return {
        args: cachedReports.map((file) => `--base-coverage=${file}`),
        disclosure: `Base coverage: nearest default-branch cache${label} — no saved report for \`${shortBase}\` itself, so coverage trends may compare against an older commit.`,
      };
    }
  }

  // Rung 5 — absent. Coverage cells show head values without a base
  // to compare against (`85 (main: n/a)` on changed files, `85 🆕` on
  // new ones), never fabricated regressions.
  return {
    args: [],
    disclosure: `Base coverage: unavailable for \`${shortBase}\` — coverage values are shown without a base to compare against, not as trends.`,
  };
}

/**
 * Fetch the codecov commit report for the PR base SHA and convert it
 * to LCOV. Returns null (never throws) when codecov has no usable
 * report — the ladder degrades instead. A `pending` report state is
 * retried briefly; a 404 means no upload exists for that SHA and is
 * final.
 */
async function fetchCodecovBaseReport(context) {
  const [owner, repo] = context.repository.split("/");
  if (!owner || !repo) {
    return null;
  }
  const token = input("CODECOV_TOKEN").trim();
  const url = `https://api.codecov.io/api/v2/github/${encodeURIComponent(owner)}/repos/${encodeURIComponent(repo)}/report/?sha=${encodeURIComponent(context.baseSha)}`;
  for (let attempt = 1; attempt <= CODECOV_PENDING_RETRIES; attempt += 1) {
    let payload;
    try {
      const headers = {
        Accept: "application/json",
        "User-Agent": "mehen-action",
      };
      if (token) {
        headers.Authorization = `bearer ${token}`;
      }
      const response = await fetch(url, { headers });
      if (response.status === 404) {
        console.log(
          `codecov has no report for base ${context.baseSha}; trying the next base-coverage source.`,
        );
        return null;
      }
      if (!response.ok) {
        console.warn(
          `codecov API responded ${response.status} for base ${context.baseSha}; trying the next base-coverage source.`,
        );
        return null;
      }
      payload = await response.json();
    } catch (error) {
      console.warn(
        `codecov API request failed (${error.message}); trying the next base-coverage source.`,
      );
      return null;
    }
    if (payload && payload.state === "pending") {
      console.log(
        `codecov report for ${context.baseSha} is still processing (attempt ${attempt}/${CODECOV_PENDING_RETRIES}).`,
      );
      if (attempt < CODECOV_PENDING_RETRIES) {
        await sleep(CODECOV_RETRY_DELAY_MS);
      }
      continue;
    }
    const lcov = codecovToLcov(payload);
    if (!lcov) {
      console.log(
        `codecov report for ${context.baseSha} carries no per-file line data; trying the next base-coverage source.`,
      );
    }
    return lcov;
  }
  console.warn(
    `codecov report for ${context.baseSha} stayed pending; trying the next base-coverage source.`,
  );
  return null;
}

/**
 * Convert a codecov API v2 commit report to LCOV `SF:`/`DA:` records.
 *
 * `line_coverage` entries are `[line, status]` pairs with
 * 0 = hit, 1 = miss, 2 = partial (verified against this repository's
 * own codecov data for 0/1; 2 follows codecov's documented session
 * encoding). A partial line executed, so it maps to a hit — and no
 * `BRDA` records are fabricated: codecov's merged view does not
 * preserve original branch arms, and invented arms would poison
 * `coverage.branch` gates. Unknown statuses and malformed entries are
 * skipped (measured-or-absent). Returns null when no file yields any
 * line record — an empty LCOV file would fail mehen's format sniff,
 * and "absent with disclosure" is the honest degradation.
 */
function codecovToLcov(report) {
  const files = Array.isArray(report?.files) ? report.files : [];
  let out = "";
  for (const file of files) {
    const name = typeof file?.name === "string" ? file.name.trim() : "";
    const lines = Array.isArray(file?.line_coverage) ? file.line_coverage : [];
    if (!name || lines.length === 0) {
      continue;
    }
    let records = "";
    for (const entry of lines) {
      if (!Array.isArray(entry) || entry.length < 2) {
        continue;
      }
      const [line, status] = entry;
      if (!Number.isInteger(line) || line <= 0) {
        continue;
      }
      if (status === 0 || status === 2) {
        records += `DA:${line},1\n`;
      } else if (status === 1) {
        records += `DA:${line},0\n`;
      }
    }
    if (!records) {
      continue;
    }
    out += `SF:${name}\n${records}end_of_record\n`;
  }
  return out || null;
}

/**
 * Whether a failed `mehen diff` invocation is attributable to one of
 * the *base-side* coverage reports: mehen's coverage setup errors name
 * the offending report path on stderr ("cannot read coverage report
 * `PATH`", "failed to parse coverage report `PATH`", "unrecognized
 * coverage report format: `PATH`"). Matching on the base paths keeps
 * the degradation retry away from unrelated failures — including a
 * corrupt *head* report, which is the caller's own fresh artifact and
 * must keep failing loudly on its own step.
 */
function isBaseCoverageFailure(error, baseArgs) {
  const stderr = typeof error?.stderr === "string" ? error.stderr : "";
  if (!stderr || !Array.isArray(baseArgs) || baseArgs.length === 0) {
    return false;
  }
  return baseArgs.some((arg) => {
    const reportPath = String(arg).replace(/^--base-coverage=/, "");
    return reportPath.length > 0 && stderr.includes(reportPath);
  });
}

/**
 * Pick the workflow artifact holding the base revision's coverage
 * reports: non-expired, produced by a run whose head SHA is exactly
 * the PR base SHA. Several runs can produce the same-named artifact
 * for one SHA (re-runs, multiple workflows) — the newest upload wins.
 */
function pickBaseArtifact(artifacts, baseSha) {
  if (!Array.isArray(artifacts) || !baseSha) {
    return null;
  }
  const candidates = artifacts.filter(
    (artifact) =>
      artifact &&
      artifact.expired !== true &&
      artifact.workflow_run?.head_sha === baseSha,
  );
  if (candidates.length === 0) {
    return null;
  }
  candidates.sort(
    (a, b) => new Date(b.created_at ?? 0) - new Date(a.created_at ?? 0),
  );
  return candidates[0];
}

/**
 * Fetch base-revision coverage reports from a workflow artifact
 * (rung 2). Returns the extracted file paths, or null (never throws)
 * so the ladder degrades: missing artifact, expired entry, oversized
 * archive, download or extraction failure all fall through to the
 * next source. Needs `actions: read` on the token; a 403 therefore
 * degrades with a permission hint rather than failing the action.
 */
async function fetchArtifactBaseReports(context, artifactName) {
  const token = input("GITHUB_TOKEN").trim() || process.env.GITHUB_TOKEN || "";
  const [owner, repo] = context.repository.split("/");
  if (!owner || !repo || !token) {
    return null;
  }
  // Listings are newest-first across all runs, so the base SHA's
  // artifact can sit past the first page in a busy repository; the
  // first page containing a match holds the newest match overall.
  // The page budget keeps a pathological history from stalling the
  // rung — beyond it, the lower rungs serve better than a long walk.
  let artifact = null;
  try {
    for (let page = 1; page <= ARTIFACT_MAX_PAGES; page += 1) {
      const listing = await githubRequest(
        "GET",
        `/repos/${owner}/${repo}/actions/artifacts?name=${encodeURIComponent(artifactName)}&per_page=100&page=${page}`,
        token,
      );
      const artifacts = Array.isArray(listing?.artifacts)
        ? listing.artifacts
        : [];
      artifact = pickBaseArtifact(artifacts, context.baseSha);
      if (artifact || artifacts.length < 100) {
        break;
      }
    }
  } catch (error) {
    const hint = String(error.message).includes(" 403 ")
      ? " (does the job grant `actions: read`?)"
      : "";
    console.warn(
      `artifact lookup for '${artifactName}' failed${hint}: ${error.message}; trying the next base-coverage source.`,
    );
    return null;
  }
  if (!artifact) {
    console.log(
      `no '${artifactName}' artifact found for base ${context.baseSha}; trying the next base-coverage source.`,
    );
    return null;
  }
  const size = Number(artifact.size_in_bytes);
  if (Number.isFinite(size) && size > ARTIFACT_MAX_BYTES) {
    console.warn(
      `artifact '${artifactName}' for base ${context.baseSha} is ${size} bytes (cap ${ARTIFACT_MAX_BYTES}); trying the next base-coverage source.`,
    );
    return null;
  }
  try {
    // fetch follows the 302 to blob storage automatically; undici
    // drops the Authorization header on the cross-origin redirect,
    // which is exactly what the signed blob URL expects. The abort
    // signal turns a stalled blob transfer into a ladder degradation
    // instead of a job-timeout hang.
    const response = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/actions/artifacts/${artifact.id}/zip`,
      {
        headers: {
          Accept: "application/vnd.github+json",
          Authorization: `Bearer ${token}`,
          "User-Agent": "mehen-action",
          "X-GitHub-Api-Version": "2022-11-28",
        },
        signal: AbortSignal.timeout(ARTIFACT_DOWNLOAD_TIMEOUT_MS),
      },
    );
    if (!response.ok) {
      console.warn(
        `artifact download for '${artifactName}' responded ${response.status}; trying the next base-coverage source.`,
      );
      return null;
    }
    // The metadata check above trusts the API; these two enforce the
    // cap on what actually arrives (a missing size_in_bytes field or
    // a chunked response must not become an unbounded read).
    const declared = Number(response.headers.get("content-length"));
    if (Number.isFinite(declared) && declared > ARTIFACT_MAX_BYTES) {
      console.warn(
        `artifact '${artifactName}' download declares ${declared} bytes (cap ${ARTIFACT_MAX_BYTES}); trying the next base-coverage source.`,
      );
      return null;
    }
    const buffer = Buffer.from(await response.arrayBuffer());
    if (buffer.length > ARTIFACT_MAX_BYTES) {
      console.warn(
        `artifact '${artifactName}' download is ${buffer.length} bytes (cap ${ARTIFACT_MAX_BYTES}); trying the next base-coverage source.`,
      );
      return null;
    }
    const dir = path.join(
      process.env.RUNNER_TEMP || os.tmpdir(),
      "mehen-artifact-base",
    );
    fs.mkdirSync(dir, { recursive: true });
    const extracted = extractZip(buffer, dir, ARTIFACT_MAX_BYTES);
    if (extracted.length === 0) {
      console.log(
        `artifact '${artifactName}' for base ${context.baseSha} contained no files; trying the next base-coverage source.`,
      );
      return null;
    }
    return extracted;
  } catch (error) {
    console.warn(
      `artifact retrieval for '${artifactName}' failed (${error.message}); trying the next base-coverage source.`,
    );
    return null;
  }
}

/**
 * Extract a standard ZIP archive (the format GitHub serves for
 * workflow artifacts) into `destDir`, returning the extracted file
 * paths sorted. Zero-dependency by design: entries are read from the
 * central directory (whose sizes are authoritative even when a local
 * header deferred them to a data descriptor) and inflated with
 * node:zlib. Supports the two methods artifact zips use — stored (0)
 * and deflate (8); no zip64 (the artifact size cap is far below 4
 * GiB). Entries that would escape `destDir` (zip-slip) are rejected
 * loudly rather than skipped, and `maxTotalBytes` bounds the
 * *decompressed* output — checked against the declared sizes up
 * front and enforced per entry via zlib's maxOutputLength, so an
 * archive whose metadata lies (a zip bomb) aborts mid-inflate
 * instead of exhausting the runner. A hostile archive is not a
 * degradation case but an integrity failure.
 */
function extractZip(buffer, destDir, maxTotalBytes = Infinity) {
  const EOCD_SIG = 0x06054b50;
  const CENTRAL_SIG = 0x02014b50;
  const LOCAL_SIG = 0x04034b50;
  const eocdFloor = Math.max(0, buffer.length - 22 - 0xffff);
  let eocd = -1;
  for (let i = buffer.length - 22; i >= eocdFloor; i -= 1) {
    if (buffer.readUInt32LE(i) === EOCD_SIG) {
      eocd = i;
      break;
    }
  }
  if (eocd < 0) {
    throw new Error("not a zip archive (no end-of-central-directory record)");
  }
  const entryCount = buffer.readUInt16LE(eocd + 10);
  let cursor = buffer.readUInt32LE(eocd + 16);
  const extracted = [];
  let declaredTotal = 0;
  let writtenTotal = 0;
  for (let i = 0; i < entryCount; i += 1) {
    if (buffer.readUInt32LE(cursor) !== CENTRAL_SIG) {
      throw new Error("corrupt zip archive (central directory signature)");
    }
    const method = buffer.readUInt16LE(cursor + 10);
    const compressedSize = buffer.readUInt32LE(cursor + 20);
    const uncompressedSize = buffer.readUInt32LE(cursor + 24);
    const nameLength = buffer.readUInt16LE(cursor + 28);
    const extraLength = buffer.readUInt16LE(cursor + 30);
    const commentLength = buffer.readUInt16LE(cursor + 32);
    const localOffset = buffer.readUInt32LE(cursor + 42);
    const name = buffer.toString("utf8", cursor + 46, cursor + 46 + nameLength);
    cursor = cursor + 46 + nameLength + extraLength + commentLength;
    if (name.endsWith("/")) {
      continue; // directory entry
    }
    declaredTotal += uncompressedSize;
    if (declaredTotal > maxTotalBytes) {
      throw new Error(
        `zip archive declares more than ${maxTotalBytes} decompressed bytes`,
      );
    }
    const destPath = path.join(destDir, name);
    const relative = path.relative(destDir, destPath);
    if (
      name.startsWith("/") ||
      relative.startsWith("..") ||
      path.isAbsolute(relative)
    ) {
      throw new Error(`zip entry escapes the extraction directory: ${name}`);
    }
    if (buffer.readUInt32LE(localOffset) !== LOCAL_SIG) {
      throw new Error("corrupt zip archive (local header signature)");
    }
    const localNameLength = buffer.readUInt16LE(localOffset + 26);
    const localExtraLength = buffer.readUInt16LE(localOffset + 28);
    const dataStart = localOffset + 30 + localNameLength + localExtraLength;
    const data = buffer.subarray(dataStart, dataStart + compressedSize);
    let content;
    if (method === 0) {
      content = data;
    } else if (method === 8) {
      // The declared sizes above are metadata a hostile archive can
      // understate; the inflate budget is the enforcement on actual
      // output. zlib validates maxOutputLength against
      // buffer.kMaxLength — 4 GiB on Node 24 — so the unbounded case
      // omits the option entirely and finite budgets are clamped
      // below that floor (clamping down only tightens enforcement).
      if (maxTotalBytes === Infinity) {
        content = zlib.inflateRawSync(data);
      } else {
        const budget = Math.min(
          0xffffffff,
          Math.max(1, maxTotalBytes - writtenTotal),
        );
        content = zlib.inflateRawSync(data, { maxOutputLength: budget });
      }
    } else {
      throw new Error(`unsupported zip compression method ${method}: ${name}`);
    }
    writtenTotal += content.length;
    if (writtenTotal > maxTotalBytes) {
      throw new Error(
        `zip archive expands past ${maxTotalBytes} decompressed bytes`,
      );
    }
    fs.mkdirSync(path.dirname(destPath), { recursive: true });
    fs.writeFileSync(destPath, content);
    extracted.push(destPath);
  }
  return extracted.sort();
}

/** Every file under `dir`, recursively, sorted for determinism. */
function listFilesRecursively(dir) {
  if (!dir || !fs.existsSync(dir)) {
    return [];
  }
  const out = [];
  const stack = [dir];
  while (stack.length > 0) {
    const current = stack.pop();
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const full = path.join(current, entry.name);
      if (entry.isDirectory()) {
        stack.push(full);
      } else if (entry.isFile()) {
        out.push(full);
      }
    }
  }
  return out.sort();
}

function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

function prepareMehen() {
  const method = input("INSTALL_METHOD", "npm").trim().toLowerCase();

  if (method === "npm") {
    const version = input("VERSION").trim();
    const pkg = version ? `mehen@${version}` : "mehen";
    return { command: "npx", args: ["-y", pkg] };
  }

  if (method === "cargo") {
    const actionPath = process.env.GITHUB_ACTION_PATH || process.cwd();
    // The repo root is a virtual workspace manifest (no `[package]`),
    // so `cargo install --path <root>` fails with "found a virtual
    // manifest … instead of a package manifest". `cargo install
    // --path <member>` works against the `mehen` package's directory.
    const cratePath = path.join(actionPath, "crates", "mehen-cli");
    const root = path.join(
      process.env.RUNNER_TEMP || os.tmpdir(),
      "mehen-action-cli",
    );
    const bin = process.platform === "win32" ? "mehen.exe" : "mehen";
    const binPath = path.join(root, "bin", bin);

    if (!fs.existsSync(binPath)) {
      fs.rmSync(root, { recursive: true, force: true });
      runCommand(
        "cargo",
        ["install", "--path", cratePath, "--locked", "--root", root],
        {
          cwd: actionPath,
          stdio: "inherit",
        },
      );
    } else {
      console.log(`Using cached mehen binary at ${binPath}.`);
    }

    return { command: binPath, args: [] };
  }

  if (method === "path") {
    return { command: input("PATH", "mehen").trim() || "mehen", args: [] };
  }

  throw new Error(
    `Unsupported mehen install-method '${method}'. Use npm, cargo, or path.`,
  );
}

function detectMehenVersion(cli) {
  const result = spawnSync(
    cli.command,
    [...cli.args, "--version", "--json"],
    {
      encoding: "utf8",
      maxBuffer: 1024 * 1024,
    },
  );
  if (result.error || result.status !== 0) {
    return "";
  }
  return parseVersionOutput(result.stdout);
}

function parseVersionOutput(stdout) {
  const text = String(stdout ?? "").trim();
  if (!text) {
    return "";
  }
  try {
    const payload = JSON.parse(text);
    if (payload && typeof payload.version === "string") {
      return payload.version.trim();
    }
  } catch {
    // Fall through to return "" so older mehen builds without
    // `--version --json` don't break the action.
  }
  return "";
}

function runMehen(cli, args, options = {}) {
  console.log(`Running: ${[cli.command, ...cli.args, ...args].join(" ")}`);
  const result = spawnSync(cli.command, [...cli.args, ...args], {
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  });

  if (result.error) {
    throw result.error;
  }
  if (result.status !== 0) {
    // A nonzero exit that still produced the requested report is a
    // quality-gate failure (`mehen.toml` thresholds exit 1, `--fail-on`
    // documentation gates exit 2), not a broken run: surface the
    // stderr report in the log, keep the stdout report so the PR
    // comment and outputs still land, and let the caller defer the
    // failure. Everything else keeps failing fast.
    if (
      typeof options.acceptGateOutput === "function" &&
      options.acceptGateOutput(result.stdout)
    ) {
      if (result.stderr) {
        process.stderr.write(result.stderr);
      }
      return { ...result, gateStatus: result.status };
    }
    if (result.stdout) {
      console.error(result.stdout);
    }
    if (result.stderr) {
      console.error(result.stderr);
    }
    const error = new Error(`mehen exited with status ${result.status}`);
    // Attach the streams so callers can classify the failure (e.g.
    // the base-coverage degradation retry in `main`).
    error.stdout = result.stdout;
    error.stderr = result.stderr;
    throw error;
  }
  if (result.stderr) {
    process.stderr.write(result.stderr);
  }
  return result;
}

/**
 * Whether a failing `mehen diff --output-format json` invocation is a
 * configured quality-gate exit: the payload must be complete AND carry
 * the explicit `threshold_violations` signal the CLI emits only when a
 * `mehen.toml` gate fired. An analysis failure also exits 1 with
 * well-formed JSON but without that key — it must keep failing fast
 * instead of publishing a partial report under the wrong reason.
 */
function isGateFailureReport(stdout) {
  try {
    const parsed = JSON.parse(typeof stdout === "string" ? stdout : "");
    return Boolean(
      parsed &&
        Array.isArray(parsed.source_code) &&
        Array.isArray(parsed.threshold_violations) &&
        parsed.threshold_violations.length > 0,
    );
  } catch {
    return false;
  }
}

function runCommand(command, args, options = {}) {
  const result = spawnSync(command, args, {
    encoding: "utf8",
    ...options,
  });
  if (result.error) {
    throw result.error;
  }
  if (result.status !== 0) {
    throw new Error(
      `${command} ${args.join(" ")} exited with status ${result.status}`,
    );
  }
  return result;
}

/**
 * Whether the JSON diff payload carries a documentation section — the
 * signal that a second (markdown-format) invocation would actually
 * yield a `<!-- mehen-docs -->` block worth extracting.
 */
function diffJsonHasDocs(stdout) {
  try {
    const parsed = JSON.parse(typeof stdout === "string" ? stdout : "");
    return Boolean(
      parsed && Array.isArray(parsed.markdown) && parsed.markdown.length > 0,
    );
  } catch {
    return false;
  }
}

/**
 * Re-run `mehen diff --output-format markdown` with the same scope as
 * the JSON run, then carve out the `<!-- mehen-docs -->` section per
 * §39.1. Returns null when the section is absent (no Markdown files in
 * scope) or when the CLI fails — callers treat null as "just publish
 * the source-code section".
 *
 * The rerun is forced history-free: the docs section comes from the
 * documentation pipeline (fixed `markdown.*` columns, never history),
 * and this run's source-code section is discarded — without the
 * override, the default history columns would make the rerun pay for
 * two more full repository walks that feed nothing.
 */
function fetchMarkdownDocsSection(cli, baseArgs) {
  const mdArgs = [...baseArgs];
  const fmtIdx = mdArgs.indexOf("--output-format");
  if (fmtIdx >= 0) {
    mdArgs[fmtIdx + 1] = "markdown";
  }
  const metricsIdx = mdArgs.indexOf("--metrics");
  if (metricsIdx >= 0) {
    mdArgs[metricsIdx + 1] = "cognitive";
  } else {
    mdArgs.push("--metrics", "cognitive");
  }
  let mdResult;
  try {
    // The rerun trips the same configured quality gates as the main
    // diff (exit 1 with the markdown report on stdout); accept any
    // non-empty output so the docs section still reaches the comment.
    mdResult = runMehen(cli, mdArgs, {
      acceptGateOutput: (stdout) =>
        typeof stdout === "string" && stdout.trim().length > 0,
    });
  } catch (error) {
    console.warn(
      `mehen diff --output-format markdown failed (docs section will be omitted): ${error.message}`,
    );
    return null;
  }
  return extractMarkdownDocsSection(mdResult?.stdout ?? "");
}

/**
 * Pure extractor for the `<!-- mehen-docs -->` section so it can be
 * unit-tested without spawning the CLI. Treats any of the following as
 * "no docs section" (returns null):
 *   - input is null, undefined, or whitespace-only,
 *   - the anchor is absent,
 *   - the slice starting at the anchor contains nothing beyond the
 *     anchor itself (e.g. truncated/partial CLI output).
 */
function extractMarkdownDocsSection(stdout) {
  const body = typeof stdout === "string" ? stdout : "";
  if (!body.trim()) {
    return null;
  }
  const anchor = "<!-- mehen-docs -->";
  const start = body.indexOf(anchor);
  if (start < 0) {
    return null;
  }
  // Anchor through end-of-output is the docs section — §39.1 places
  // the anchor at the start of the section and the CLI never emits
  // anything after it.
  const section = body.slice(start).trim();
  // An anchor-only output (no headline/table/callouts after it) is
  // effectively empty — treat as missing rather than publishing a bare
  // comment marker into the sticky PR comment.
  if (section === anchor) {
    return null;
  }
  return section;
}

function parseDiffJson(stdout) {
  try {
    const parsed = JSON.parse(stdout);
    // Phase F (§39) introduced the `{ source_code: [...], markdown?: ... }`
    // shape so a single `mehen diff --output-format json` run can carry
    // both sections. Accept either the new object form or the legacy
    // top-level array for backward compatibility with older mehen CLIs.
    if (Array.isArray(parsed)) {
      return parsed;
    }
    if (parsed && Array.isArray(parsed.source_code)) {
      return parsed.source_code;
    }
    throw new Error(
      "mehen diff JSON output was not an array or {source_code: [...]} object",
    );
  } catch (error) {
    throw new Error(
      `Failed to parse mehen diff JSON: ${error.message}\n${stdout}`,
    );
  }
}

function readGithubContext() {
  let payload = {};
  const eventPath = process.env.GITHUB_EVENT_PATH;
  if (eventPath && fs.existsSync(eventPath)) {
    payload = JSON.parse(fs.readFileSync(eventPath, "utf8"));
  }

  const pullRequest = payload.pull_request;
  return {
    eventName: process.env.GITHUB_EVENT_NAME || "",
    repository: process.env.GITHUB_REPOSITORY || "",
    sha: pullRequest?.head?.sha || process.env.GITHUB_SHA || "",
    baseSha: pullRequest?.base?.sha || "",
    baseLabel: pullRequest?.base?.ref || input("FROM").trim() || "base",
    prNumber: pullRequest?.number || payload.number || null,
    token: input("GITHUB_TOKEN").trim() || process.env.GITHUB_TOKEN || "",
  };
}

/**
 * The `threshold_violations` array a gate-failing `mehen diff` embeds
 * in its JSON report (absolute `mehen.toml` breaches at head — see the
 * Configuration docs). Empty for passing runs, older CLIs, and
 * non-JSON output.
 */
function parseGateViolations(stdout) {
  try {
    const parsed = JSON.parse(typeof stdout === "string" ? stdout : "");
    return parsed && Array.isArray(parsed.threshold_violations)
      ? parsed.threshold_violations
      : [];
  } catch {
    return [];
  }
}

function renderMarkdown(
  diffs,
  context,
  thresholds,
  violations,
  version = "",
  gateViolations = [],
  coverageNote = null,
) {
  const title = input("COMMENT_TITLE", DEFAULT_TITLE).trim() || DEFAULT_TITLE;
  const scope =
    context.eventName === "pull_request"
      ? ` (this PR vs \`${context.baseLabel}\`)`
      : "";
  let body = `${MARKER}\n${title}${scope}\n\n`;

  let sawNotApplicable = false;

  if (diffs.length === 0) {
    body += "No metric changes detected.\n";
  } else {
    const metrics = unionMetricColumns(diffs);
    body += "| File |";
    for (const metric of metrics) {
      body += ` ${escapeCell(metric.label || metric.name)} |`;
    }
    body += "\n|---|";
    for (const _metric of metrics) {
      body += "---:|";
    }
    body += "\n";

    for (const file of diffs) {
      body += `| ${renderFile(file.path, context)} |`;
      const row = alignFileMetrics(file.metrics || [], metrics);
      for (const metric of row) {
        if (isNotApplicable(metric)) {
          sawNotApplicable = true;
        }
        body += ` ${escapeCell(formatMetricCell(metric, context.baseLabel))} |`;
      }
      body += "\n";
    }
  }

  if (thresholds.size > 0) {
    body += "\n### Thresholds\n\n";
    if (violations.length === 0) {
      body += "All configured thresholds passed.\n";
    } else {
      body += "| File | Metric | Delta | Limit |\n";
      body += "|---|---|---:|---:|\n";
      for (const violation of violations) {
        body += `| ${renderFile(violation.path, context)} | ${escapeCell(violation.label)} | ${formatSigned(violation.delta)} | ${formatNumber(violation.limit)} |\n`;
      }
    }
  }

  // Absolute `mehen.toml` breaches at head: the diff table above may
  // not name these files at all (an unchanged-but-over-limit metric
  // is dropped as an unchanged row), so the failing gate must be
  // spelled out here or the comment would say "no changes" while the
  // workflow step fails.
  if (gateViolations.length > 0) {
    body += "\n### Repository thresholds (mehen.toml)\n\n";
    body += "| File | Metric | Value | Limit | Set by |\n";
    body += "|---|---|---:|---:|---|\n";
    for (const violation of gateViolations) {
      const bound = violation.polarity === "higher_is_better" ? "min" : "max";
      body += `| ${renderFile(violation.path, context)} | ${escapeCell(violation.metric)} | ${formatExactNumber(violation.value)} | ${bound} ${formatExactNumber(violation.limit)} | ${escapeCell(violation.source_table)} |\n`;
    }
  }

  if (sawNotApplicable) {
    body +=
      "\n> `—` indicates the metric does not apply to the file's language.\n";
  }

  // Base-coverage source disclosure (issue #248): every rung of the
  // retrieval ladder is stated — never silently.
  if (coverageNote) {
    body += `\n> ${coverageNote}\n`;
  }

  body += `\n${renderFooter(version)}\n`;

  return body;
}

function renderFooter(version) {
  const trimmed = String(version ?? "").trim();
  const versionSuffix = trimmed ? ` v${trimmed}` : "";
  return `${FOOTER_PREFIX}${versionSuffix} ${FOOTER_SUFFIX}`;
}

function renderFile(filePath, context) {
  const escaped = escapeCell(filePath);
  if (!context.repository || !context.sha) {
    return escaped;
  }
  const urlPath = String(filePath)
    .split("/")
    .map((part) => encodeURIComponent(part))
    .join("/");
  return `[${escaped}](https://github.com/${context.repository}/blob/${context.sha}/${urlPath})`;
}

// Build the master header as the union of metrics across all files, preserving
// first-seen order. Using `diffs[0].metrics` alone would silently drop any
// metric that only appears in later files (e.g. when the first file omits it
// under the language-applicability rules).
function unionMetricColumns(diffs) {
  const seen = new Map();
  for (const file of diffs) {
    for (const metric of file.metrics || []) {
      const key = metric && (metric.name || metric.label);
      if (key && !seen.has(key)) {
        seen.set(key, metric);
      }
    }
  }
  return [...seen.values()];
}

// Normalize a file's metric list against the header's master list so that a
// file which omits a metric still produces a cell in the row. Missing metrics
// are filled with a placeholder that isNotApplicable() recognizes, so they
// render as `—`.
function alignFileMetrics(fileMetrics, headerMetrics) {
  const byKey = new Map();
  for (const m of fileMetrics) {
    if (m && (m.name || m.label)) {
      byKey.set(m.name || m.label, m);
    }
  }
  return headerMetrics.map((h) => {
    const key = h.name || h.label;
    const found = byKey.get(key);
    if (found) {
      return found;
    }
    return {
      name: h.name,
      label: h.label,
      not_applicable: true,
      current: null,
      baseline: null,
      delta: 0,
      polarity: h.polarity,
    };
  });
}

function isNotApplicable(metric) {
  if (!metric) {
    return true;
  }
  if (metric.not_applicable === true) {
    return true;
  }
  const current = metric.current;
  const baseline = metric.baseline;
  const missing = (v) => v === null || v === undefined;
  return missing(current) && missing(baseline);
}

function formatMetricCell(metric, baseLabel) {
  if (isNotApplicable(metric)) {
    return "—";
  }
  // A side flagged unavailable carries a numeric `0.0` placeholder
  // that is *not* a measurement (static analysis was impossible for
  // that side — undecodable content, blocking parse diagnostic, or a
  // feature-gated analyzer). Render `n/a` and claim no trend, exactly
  // like the native CLI table.
  const currentUnavailable = metric.current_unavailable === true;
  const baselineUnavailable = metric.baseline_unavailable === true;
  const current = currentUnavailable ? "n/a" : formatNumber(metric.current);
  if (metric.is_new) {
    return `${current} \u{1F195}`;
  }
  if (metric.is_deleted) {
    if (baselineUnavailable) {
      return "0 (was: n/a)";
    }
    return `0 (was: ${formatNumber(metric.baseline)}) ${trendEmoji(metric)}`;
  }
  if (currentUnavailable || baselineUnavailable) {
    if (currentUnavailable && baselineUnavailable) {
      return "n/a";
    }
    const baseline = baselineUnavailable ? "n/a" : formatNumber(metric.baseline);
    return `${current} (${baseLabel}: ${baseline})`;
  }
  if (Number(metric.delta) === 0) {
    return `${current} \u{26AA}`;
  }
  return `${current} (${baseLabel}: ${formatNumber(metric.baseline)}) ${trendEmoji(metric)}`;
}

function trendEmoji(metric) {
  const delta = Number(metric.delta);
  if (delta === 0) {
    return "\u{26AA}";
  }
  const polarity = metric.polarity || inferPolarity(metric.name);
  if (polarity === HIGHER_IS_BETTER) {
    return delta > 0 ? "\u{1F7E2}" : "\u{1F534}";
  }
  return delta > 0 ? "\u{1F534}" : "\u{1F7E2}";
}

function collectThresholdViolations(diffs, thresholds) {
  const violations = [];
  if (thresholds.size === 0) {
    return violations;
  }

  for (const file of diffs) {
    for (const metric of file.metrics || []) {
      if (isNotApplicable(metric)) {
        continue;
      }
      // An unavailable side means the delta is a placeholder, not a
      // measured change — never a threshold violation.
      if (metric.current_unavailable === true || metric.baseline_unavailable === true) {
        continue;
      }
      const key = canonicalMetricName(metric.name || metric.label || "");
      const labelKey = canonicalMetricName(metric.label || metric.name || "");
      const limit = thresholds.get(key) ?? thresholds.get(labelKey);
      if (limit === undefined) {
        continue;
      }

      const adverseDelta = getAdverseDelta(metric);
      if (adverseDelta > limit) {
        violations.push({
          path: file.path,
          label: metric.label || metric.name,
          delta: Number(metric.delta),
          limit,
        });
      }
    }
  }

  return violations;
}

function getAdverseDelta(metric) {
  const delta = Number(metric.delta);
  const polarity = metric.polarity || inferPolarity(metric.name);
  if (polarity === HIGHER_IS_BETTER) {
    return delta < 0 ? Math.abs(delta) : 0;
  }
  return delta > 0 ? delta : 0;
}

function parseThresholds(value) {
  const thresholds = new Map();
  for (const raw of parseList(value)) {
    const match = raw.match(
      /^([^:=<>]+)\s*(?:<=|=|:)\s*([0-9]+(?:\.[0-9]+)?)$/,
    );
    if (!match) {
      throw new Error(`Invalid threshold '${raw}'. Expected metric=number.`);
    }
    thresholds.set(canonicalMetricName(match[1]), Number(match[2]));
  }
  return thresholds;
}

function canonicalMetricName(name) {
  const raw = String(name)
    .replace(/[\s_-]+/g, "")
    .replace(/\.+/g, ".");
  // `halstead.n1`/`halstead.N1` and `halstead.n2`/`halstead.N2` are
  // case-distinct published keys (distinct vs total operator/operand
  // counts): lowercasing would collapse a threshold onto the wrong
  // measurement, so their case is preserved verbatim.
  if (/^halstead\.[nN][12]$/.test(raw)) {
    return raw;
  }
  const normalized = raw.toLowerCase();
  return METRIC_ALIASES.get(normalized) || normalized;
}

function inferPolarity(name) {
  const canonical = canonicalMetricName(name);
  return canonical === "mi" || canonical.startsWith("mi.")
    ? HIGHER_IS_BETTER
    : LOWER_IS_BETTER;
}

function formatNumber(value) {
  const number = Number(value);
  if (!Number.isFinite(number)) {
    return String(value);
  }
  return Number.isInteger(number) ? String(number) : number.toFixed(2);
}

/**
 * Shortest exact representation for repository-gate values: rounding
 * both sides of a close crossing to two decimals would render an
 * apparently impossible failure (`0.50` versus `max 0.50` for a
 * `0.504` value over a `0.503` limit).
 */
function formatExactNumber(value) {
  const number = Number(value);
  return Number.isFinite(number) ? String(number) : String(value);
}

function formatSigned(value) {
  const number = Number(value);
  if (!Number.isFinite(number)) {
    return String(value);
  }
  const formatted = formatNumber(number);
  return number > 0 ? `+${formatted}` : formatted;
}

function escapeCell(value) {
  return String(value).replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function writeStepSummary(markdown) {
  const summary = process.env.GITHUB_STEP_SUMMARY;
  if (summary) {
    fs.appendFileSync(summary, `${markdown}\n`, "utf8");
  }
}

async function maybeComment(markdown, context) {
  if (!boolInput("COMMENT", true) || context.eventName !== "pull_request") {
    return;
  }
  if (!context.repository || !context.prNumber) {
    console.log(
      "Skipping mehen PR comment because pull request context is unavailable.",
    );
    return;
  }
  if (!context.token) {
    console.log(
      "Skipping mehen PR comment because github-token is unavailable.",
    );
    return;
  }

  const [owner, repo] = context.repository.split("/");
  const comments = await listComments(
    owner,
    repo,
    context.prNumber,
    context.token,
  );
  const title = input("COMMENT_TITLE", DEFAULT_TITLE).trim() || DEFAULT_TITLE;
  const previous = comments.find(
    (comment) =>
      comment.body?.includes(MARKER) || comment.body?.startsWith(title),
  );

  if (previous) {
    await githubRequest(
      "PATCH",
      `/repos/${owner}/${repo}/issues/comments/${previous.id}`,
      context.token,
      { body: markdown },
    );
    console.log(`Updated mehen metrics comment ${previous.id}.`);
  } else {
    await githubRequest(
      "POST",
      `/repos/${owner}/${repo}/issues/${context.prNumber}/comments`,
      context.token,
      { body: markdown },
    );
    console.log("Created mehen metrics comment.");
  }
}

async function listComments(owner, repo, issueNumber, token) {
  const comments = [];
  for (let page = 1; ; page += 1) {
    const batch = await githubRequest(
      "GET",
      `/repos/${owner}/${repo}/issues/${issueNumber}/comments?per_page=100&page=${page}`,
      token,
    );
    comments.push(...batch);
    if (batch.length < 100) {
      return comments;
    }
  }
}

async function githubRequest(method, apiPath, token, body = undefined) {
  const response = await fetch(`https://api.github.com${apiPath}`, {
    method,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "User-Agent": "mehen-action",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    body: body === undefined ? undefined : JSON.stringify(body),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(
      `GitHub API ${method} ${apiPath} failed: ${response.status} ${text}`,
    );
  }

  if (response.status === 204) {
    return null;
  }

  return response.json();
}

function setOutput(name, value) {
  const output = process.env.GITHUB_OUTPUT;
  if (output) {
    fs.appendFileSync(output, `${name}=${value}\n`, "utf8");
  }
}

export {
  DEFAULT_TEST_EXCLUDES,
  alignFileMetrics,
  buildDiffArgs,
  canonicalMetricName,
  codecovToLcov,
  collectThresholdViolations,
  diffJsonHasDocs,
  extractMarkdownDocsSection,
  extractZip,
  formatMetricCell,
  inferPolarity,
  isBaseCoverageFailure,
  isGateFailureReport,
  isNotApplicable,
  listFilesRecursively,
  parseGateViolations,
  parseList,
  parseThresholds,
  parseVersionOutput,
  pickBaseArtifact,
  renderFooter,
  unionMetricColumns,
};
